spring:
  profiles:
    active: pro

---
# 开发
spring:
  profiles: dev
server:
  port: 9001
---
# 生产
spring:
  profiles: pro
server:
  port: 9002
---
# 测试
spring:
  profiles: test
server:
  port: 9003
---
